// Generated by CoffeeScript 1.6.2
(function() {
  var BbExpert, DEBUG, binPath, childProcess, path, phantomjs, requestify, util;

  util = require('util');

  requestify = require('requestify');

  childProcess = require('child_process');

  phantomjs = require('phantomjs');

  binPath = phantomjs.path;

  path = require('path');

  DEBUG = true;

  BbExpert = (function() {
    function BbExpert(game, expertIndex) {
      this.game = game;
      this.expertIndex = expertIndex;
      this.bbhelper = 'bbhelper.js';
    }

    BbExpert.prototype.getNextGuess = function() {
      var childArgs, expert, missed, word;

      DEBUG && this.game.log('bb\'s getnextguess is called');
      expert = this;
      word = this.game.currentWord;
      missed = this.game.missed;
      childArgs = [path.join(__dirname, this.bbhelper), encodeURIComponent(word.replace(/\*/g, '?')), encodeURIComponent(missed)];
      return childProcess.execFile(binPath, childArgs, function(err, stdout, stderr) {
        var result;

        result = JSON.parse(stdout);
        return expert.game.vote.apply(expert.game, [result.choice, expert.expertIndex]);
      });
    };

    return BbExpert;

  })();

  exports.BbExpert = BbExpert;

}).call(this);
