// Generated by CoffeeScript 1.6.2
(function() {
  var BbExpert, Browser, DEBUG, requestify, util;

  util = require('util');

  requestify = require('requestify');

  Browser = require('zombie');

  DEBUG = true;

  BbExpert = (function() {
    function BbExpert(game, expertIndex) {
      this.game = game;
      this.expertIndex = expertIndex;
      this.requestUrl = 'http://blogmybrain.com/hanging-with-friends-cheat/';
      this.browser = new Browser();
      this.browser.visit(this.requestUrl);
    }

    BbExpert.prototype.getNextGuess = function() {
      var expert, missed, word;

      DEBUG && this.game.log('bb\'s getnextguess is called');
      expert = this;
      word = this.game.currentWord;
      missed = this.game.missed;
      return this.browser.visit(this.requestUrl, {
        silent: true
      }, function(e, b) {
        return setTimeout(function() {
          DEBUG && console.log('page opened');
          expert.browser.fill.apply(expert.browser, ['#pz', word.replace(/\*/g, '?')]);
          expert.browser.fill.apply(expert.browser, ['#incorrects', missed]);
          DEBUG && console.log('about to submit');
          return expert.browser.pressButton.apply(expert.browser, [
            'Guess Word', function() {
              var choice;

              DEBUG && console.log('form submitted');
              if (expert.browser.window.document.querySelector('#pick0') && (expert.browser.window.document.querySelector('#pick0').parentNode.childNodes.length === 31)) {
                choice = '?';
              } else {
                choice = expert.browser.query('#pick0').parentNode.childNodes[7].value;
              }
              return expert.game.vote.apply(expert.game, [choice, expert.expertIndex]);
            }
          ]);
        }, 0);
      });
    };

    return BbExpert;

  })();

  exports.BbExpert = BbExpert;

}).call(this);
