// Generated by CoffeeScript 1.6.2
(function() {
  var DEBUG, HwfcExpert, binPath, childProcess, path, phantomjs, requestify, util;

  util = require('util');

  requestify = require('requestify');

  childProcess = require('child_process');

  phantomjs = require('phantomjs');

  binPath = phantomjs.path;

  path = require('path');

  DEBUG = false;

  HwfcExpert = (function() {
    function HwfcExpert(game, expertIndex) {
      this.game = game;
      this.expertIndex = expertIndex;
      this.helper = 'hwfchelper.js';
    }

    HwfcExpert.prototype.getNextGuess = function() {
      var childArgs, expert, missed, word;

      DEBUG && this.game.log('hwfc\'s getnextguess is called');
      expert = this;
      word = this.game.currentWord;
      missed = this.game.missed;
      if (word.length < 4 || word.length > 8) {
        expert.game.vote.apply(expert.game, ['?', expert.expertIndex]);
        return;
      }
      childArgs = [path.join(__dirname, this.helper), word.replace(/\*/g, '?'), missed];
      return childProcess.execFile(binPath, childArgs, function(err, stdout, stderr) {
        var result;

        result = JSON.parse(stdout);
        return expert.game.vote.apply(expert.game, [result.choice, expert.expertIndex]);
      });
    };

    return HwfcExpert;

  })();

  exports.HwfcExpert = HwfcExpert;

}).call(this);
