// Generated by CoffeeScript 1.6.2
(function() {
  var DEBUG, NmExpert, cheerio, requestify, util;

  util = require('util');

  requestify = require('requestify');

  cheerio = require('cheerio');

  DEBUG = false;

  NmExpert = (function() {
    function NmExpert(game, expertIndex) {
      this.game = game;
      this.expertIndex = expertIndex;
      this.requestUrl = 'http://nmichaels.org/hangsolve.py';
    }

    NmExpert.prototype.getNextGuess = function() {
      var expert, missed, word;

      DEBUG && this.game.log('nm\'s getnextguess is called');
      expert = this;
      word = this.game.currentWord;
      missed = this.game.missed;
      return requestify.post(this.requestUrl, {
        pattern: word.replace(/\*/g, '?'),
        exclusions: missed
      }).then(function(response) {
        var body, choices, result;

        body = JSON.parse(response.body);
        choices = Object.keys(body.recs);
        if (choices.length === 0) {
          result = '?';
        } else {
          result = choices[0];
        }
        return expert.game.vote.apply(expert.game, [result, this.expertIndex]);
      });
    };

    return NmExpert;

  })();

  exports.NmExpert = NmExpert;

}).call(this);
