// Generated by CoffeeScript 1.6.2
(function() {
  var DEBUG, NmExpert, binPath, childProcess, path, phantomjs, requestify, util;

  util = require('util');

  requestify = require('requestify');

  childProcess = require('child_process');

  phantomjs = require('phantomjs');

  binPath = phantomjs.path;

  path = require('path');

  DEBUG = false;

  NmExpert = (function() {
    function NmExpert(game, expertIndex) {
      this.game = game;
      this.expertIndex = expertIndex;
      this.nmhelper = 'nmhelper.js';
    }

    NmExpert.prototype.getNextGuess = function() {
      var childArgs, expert, missed, word;

      DEBUG && this.game.log('nm\'s getnextguess is called');
      expert = this;
      word = this.game.currentWord;
      missed = this.game.missed;
      if (word.length !== 5) {
        expert.game.vote.apply(expert.game, ['?', expert.expertIndex]);
        return;
      }
      childArgs = [path.join(__dirname, this.nmhelper), word.replace(/\*/g, '?'), missed];
      return childProcess.execFile(binPath, childArgs, function(err, stdout, stderr) {
        var e, result;

        try {
          result = JSON.parse(stdout);
          return expert.game.vote.apply(expert.game, [result.choice, expert.expertIndex]);
        } catch (_error) {
          e = _error;
          return expert.game.vote.apply(expert.game, ['?', expert.expertIndex]);
        }
      });
    };

    return NmExpert;

  })();

  exports.NmExpert = NmExpert;

}).call(this);
