// Generated by CoffeeScript 1.6.2
(function() {
  var DEBUG, NmExpert, cheerio, requestify, util;

  util = require('util');

  requestify = require('requestify');

  cheerio = require('cheerio');

  DEBUG = false;

  NmExpert = (function() {
    function NmExpert(game, expertIndex) {
      this.game = game;
      this.expertIndex = expertIndex;
      this.requestUrl = 'http://nmichaels.org/hangsolve.py';
    }

    NmExpert.prototype.getNextGuess = function() {
      var expert, missed, word;

      DEBUG && this.game.log('nm\'s getnextguess is called');
      expert = this;
      word = this.game.currentWord;
      missed = this.game.missed;
      if (word.length !== 5) {
        return this.game.vote.apply(this.game, ['?', this.expertIndex]);
      } else {
        return requestify.post(this.requestUrl, {
          pattern0: word.substr(0, 1).replace('*', '').toUpperCase(),
          pattern1: word.substr(1, 1).replace('*', '').toUpperCase(),
          pattern2: word.substr(2, 1).replace('*', '').toUpperCase(),
          pattern3: word.substr(3, 1).replace('*', '').toUpperCase(),
          pattern4: word.substr(4, 1).replace('*', '').toUpperCase(),
          game: 'hangman',
          guessed: missed,
          action: 'display'
        }).then(function(response) {
          var $, result;

          $ = cheerio.load(response.body);
          console.log(response);
          if ($('.guess').length === 0) {
            result = '?';
          } else {
            result = $('.guess').first().html().trim().substr(0, 1);
          }
          return expert.game.vote.apply(expert.game, [result, this.expertIndex]);
        });
      }
    };

    return NmExpert;

  })();

  exports.NmExpert = NmExpert;

}).call(this);
