// Generated by CoffeeScript 1.6.2
(function() {
  var DEBUG, SbExpert, cheerio, requestify, util;

  util = require('util');

  requestify = require('requestify');

  cheerio = require('cheerio');

  DEBUG = false;

  SbExpert = (function() {
    function SbExpert(game, expertIndex) {
      this.game = game;
      this.expertIndex = expertIndex;
    }

    SbExpert.prototype.getNextGuess = function() {
      var expert, missed, word;

      DEBUG && this.game.log('sb\'s getnextguess is called');
      expert = this;
      word = this.game.currentWord;
      missed = this.game.missed;
      return requestify.post('http://www.scrabulizer.com/hangman/solve', {
        pattern: word.replace(/\*/g, '?'),
        failedLetters: missed
      }).then(function(response) {
        var $, choice;

        $ = cheerio.load(response.body);
        if ($('table').length === 0) {
          return expert.game.vote.apply(expert.game, ['?', expert.expertIndex]);
        } else {
          choice = $('table').first().find('td').first().html();
          DEBUG && expert.game.log.apply(expert.game, [util.format('sbexpert guesses that the charac is %s based on the word is %s and missed are %s', choice, word, missed)]);
          return expert.game.vote.apply(expert.game, [choice, expert.expertIndex]);
        }
      });
    };

    return SbExpert;

  })();

  exports.SbExpert = SbExpert;

}).call(this);
